const actionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
  GET_SIZE: "GET_SIZE"
};

export default actionTypes