const actionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
  GET_SIZE: "GET_SIZE",
  DROP_SIZE: "DROP_SIZE",
  DISPLAY_ITEM: "DISPLAY_ITEM",
  UPDATE_CART: "UPDATE_CART",
  CHECK_ADDRESS: "CHECK_ADDRESS",
  CHECK_DELIVERY: "CHECK_DELIVERY",
};

export default actionTypes